spring:
  application:
    name: elasticsearch-practice
  elasticsearch:
    rest:
      uris: http://192.168.100.133:9200
  task:
    execution:
      pool:
        core-size: 10
  profiles:
    active: ${ENV_SPRING_PROFILE}
#  data:
#    elasticsearch:
#      clusterName: elasticsearch
#      clusterNodes: 192.168.100.133:9300
#

